repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-symlinks
      - id: destroyed-symlinks
