version: "3.8"
services:
  web:
    build: .
    working_dir: /app
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    command: npm start
    ports:
      - "80:3000"
    environment:
      DB_HOST: mydb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      - mydb

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
